[package]
	edition = "2021"
	name = "project1"
	version = "0.0.0"
	workspace = ".."

[dependencies]
	lightgbm = { git = "https://github.com/Ten0/lightgbm-rs.git", rev = "ebc5262299d75cc770e21416f9e3ef8204427fba" }
